from . import account
from . import account_bank_statement
from . import fpos_top
from . import point_of_sale
from . import res_users
from . import product
from . import fpos
from . import wizard
from . import report
from . import res_partner
from . import controller
from . import invoice
from . import pos_order_report
from . import fpos_post_task